name: Build for Fedora 41

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run build script
        run: |
          chmod +x ./run.sh
          ./run.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output-fedora_41
          path: ${{ github.workspace }}/output
